services:
  backend:
    build:
      context: ./backend
    container_name: scisp_backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=scisp_integrated
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=estivakirsten1214@gmail.com
      - MAIL_PASSWORD=usqewfeqmzhdfgjo
      - MAIL_ENCRYPTION=smtps
      - MAIL_FROM_ADDRESS=estivakirsten1214@gmail.com
      - MAIL_FROM_NAME=SCISP Admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: scisp_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: scisp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: scisp_integrated
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
